### ISSUE TITLE
Elfin extension component refactor comments - extension

### ISSUE THREAD

**Issue by pekoisgood** [finnzzzz/elfin#23]
### File 
Path : elfin/extension/src/component/home/List.tsx

### Refactor comments

1.  useEffect 應該寫下面 ( line:45 )

![螢幕快照 2023-07-20 下午2 33 15](https://github.com/finnzzzz/elfin/assets/115715217/649f6b26-bf02-4463-a847-b54089ee62d0)

2. function `traverse` 重複了 (line: 80 , line: 151 )
   
![螢幕快照 2023-07-20 下午2 34 38](https://github.com/finnzzzz/elfin/assets/115715217/442802b3-64e7-4f93-b79f-3c7b8c0d6be4)

3. 感覺不用在特別 declare `obj` (line: 143)
(不太清楚所以這個 `commandsArr` 到底是 object 還是 array ?)

![螢幕快照 2023-07-20 下午2 36 16](https://github.com/finnzzzz/elfin/assets/115715217/935ac579-4712-448b-a10f-ae863b7a8744)

4.  重複 code (line: 95, line: 166)

![螢幕快照 2023-07-20 下午2 38 15](https://github.com/finnzzzz/elfin/assets/115715217/24b320bd-d82e-43e6-ae6f-b023944438dc)

![螢幕快照 2023-07-20 下午2 38 04](https://github.com/finnzzzz/elfin/assets/115715217/e2c63cb3-b17b-4376-8530-b9fbdca1b0ad)

5. 拼錯字 `extensionVariableLsit` (line: 186)

![螢幕快照 2023-07-20 下午2 41 44](https://github.com/finnzzzz/elfin/assets/115715217/4d422dc3-3adc-4b86-b549-cf29af8c0bea)

6. 拼錯字 `IitemObj` (line: 9)

![螢幕快照 2023-07-20 下午2 49 01](https://github.com/finnzzzz/elfin/assets/115715217/32dc41f7-2ac5-4ebc-bee3-5d42135eac78)

7. Arrow function 跟 function expression 混用

![螢幕快照 2023-07-20 下午3 12 21](https://github.com/finnzzzz/elfin/assets/115715217/e5121936-9166-480f-a253-89c16ab668d1)

### Things I appreciate
1.  解構 (line: 37, line: 149)
2.  使用 recursion  (line: 84)
3.  function / variable 命名清楚

**Comment by Surfer-Alex** [comment]
@finnzzzz Have you fixed it?

**Comment by Surfer-Alex** [comment]
@finnzzzz Please let me know when u fixed,I need ELFFFFFFFFIN!

**Comment by natefzz** [comment]
@Surfer-Alex Yes, it's all fixed.
